- hosts: vpn
  collections:
    - vultr.cloud
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/vpn/main.yml
  roles:
    - snider.server_base
    - geerlingguy.glusterfs
    - ../../roles/openvpn

