- hosts: all
  collections:
    - vultr.cloud
  tasks:
    - name: Include vars for OpenVPN installation
      include_vars: "{{ item }}"
      with_first_found:
        - "./vars/{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
        - "./vars/{{ ansible_distribution }}.yml"
        - "./vars/{{ ansible_os_family }}.yml"
        - "./vars/main.yml"
    - name: install
      import_tasks: tasks/install.yml
    - name: Setup iptables
      import_tasks: tasks/setup-iptables.yml
  handlers:
    - name: save iptables rules (Debian/Ubuntu and CentOS/RHEL/Fedora)
      shell: "{{ iptables_save_command }}"  # noqa command-instead-of-shell
      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
      listen: "save iptables"