- hosts: all
  collections:
    - vultr.cloud
  vars_files:
    - group_vars/main.yml
  tasks:
    - name: Mount Gluster dir
      mount:
        name: /home/{{ created_username }}/profile
        src: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:vpn-profiles"
        fstype: glusterfs
        state: mounted

