collections:
  - name: vultr.cloud
  - name: ansible.posix
  - name: community.general
roles:
  - name: geerlingguy.ntp
  - name: geerlingguy.glusterfs
  - name: geerlingguy.nginx
  - name: geerlingguy.postgresql
  - name: geerlingguy.nodejs
  - name: geerlingguy.supervisor
  - name: geerlingguy.swap
  - name: geerlingguy.pip