- hosts: squid
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/networking/squid.yml
  tasks:
    - name: Install Squid
      ansible.builtin.shell:
      ignore_errors: true
      args:
        cmd: |
          wget https://raw.githubusercontent.com/serverok/squid-proxy-installer/master/squid3-install.sh -O squid3-install.sh
          bash squid3-install.sh
    - name: Install Squid
      ansible.builtin.shell:
      args:
        cmd: |
          /usr/bin/htpasswd -b /etc/squid/passwd {{ proxy_username }} {{ proxy_password }}
          systemctl reload squid
    - name: Adds Swap Space
      ansible.builtin.include_role:
        name: geerlingguy.swap
    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
