- hosts: squid
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/networking/squid.yml
  roles:
    - ../../roles/server_base
  tasks:
    - name: Install Squid
      ansible.builtin.shell:
      ignore_errors: true
      args:
        cmd: |
          wget https://raw.githubusercontent.com/serverok/squid-proxy-installer/master/squid3-install.sh -O squid3-install.sh
          bash squid3-install.sh
    - name: Install Squid
      ansible.builtin.shell:
      args:
        cmd: |
          /usr/bin/htpasswd -bc /etc/squid/passwd {{ proxy_username }} {{ proxy_password }}
          systemctl reload squid
