---
- name: Include vars for OpenVPN installation
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/main.yml"
- name: Install iptables-persistent (Debian/Ubuntu)
  package:
    name: "{{ package_name_iptables_persistent }}"
    state: present
  register: __iptables_installed
  when: ansible_os_family == "Debian"

- name: Install openvpn
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package_name_openvpn }}"
    - "{{ package_name_openssl }}"

- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: true
