# Add your hosts here
# You can use the following example as a template
# Example Simple Hosts File:
# all:
#   hosts:
#     hostname.example.com:
#       ansible_user: root
#     host1.example.com:
#       ansible_user: root
#
# Example Complex Hosts File:
# all:
#  children:
#    europe:
#      children:
#        london:
#          hosts:
#            hostname.example.com
#              ansible_user: root
#    asia:
#      children:
#        sydney:
#          hosts:
#            hostname.example.com
#              ansible_user: root