---
- name: Install iptables-persistent (Debian/Ubuntu)
  package:
    name: "{{ package_name_iptables_persistent }}"
    state: present
  register: __iptables_installed
  when: ansible_os_family == "Debian"

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package_name_openvpn }}"
    - "{{ package_name_openssl }}"

- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: true

- name: Setup iptables
  include_tasks: iptables.yml
  when: ansible_os_family == "Debian"