---
- name: Install iptables-persistent (Debian/Ubuntu)
  package:
    name: "{{ package_name_iptables_persistent }}"
    state: present
  register: __iptables_installed
  when: ansible_os_family == "Debian"

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package_name_openvpn }}"
    - "{{ package_name_openssl }}"

- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: true

- name: Copy Shell Files
  copy: src=bin dest=/home/{{ created_username }} mode=0777 owner={{ created_username }} group={{ created_username }}

- name: Copy Openvpn Config
  copy: src=cert-auth-ftm.conf dest=/home/{{ created_username }} mode=0644 owner={{ created_username }} group={{ created_username }}

- name: Copy Openvpn Conf dir
  copy: src=conf dest=/home/{{ created_username }} mode=0644 owner={{ created_username }} group={{ created_username }}

- name: Copy Openvpn profile dir
  copy: src=profile dest=/home/{{ created_username }} mode=0644 owner={{ created_username }} group={{ created_username }}

- name: Setup iptables
  include_tasks: iptables.yml
  when: ansible_os_family == "Debian"
